// Mock data for Tanod Management System

export const mockTanodProfiles = [
  {
    id: '1',
    firstName: 'Pedro',
    lastName: 'Santos',
    fullName: 'Pedro Santos',
    email: 'pedro.santos@barangay.gov.ph',
    phone: '+63 912 345 6789',
    emergencyContact: {
      name: 'Maria Santos',
      relationship: 'Spouse',
      phone: '+63 912 345 6780',
    },
    dateOfBirth: new Date('1985-03-15'),
    address: 'Purok 1, Barangay Hall',
    photo: null,
    status: 'active',
    currentShift: 'day',
    assignedAreas: ['Purok 1-3', 'Main Road'],
    qualifications: ['First Aid Certified', 'Crisis Management', 'Community Policing'],
    dateJoined: new Date('2020-01-15'),
    rating: 4.8,
    totalIncidentsResponded: 45,
    totalDutyHours: 1200,
  },
  {
    id: '2',
    firstName: 'Maria',
    lastName: 'Garcia',
    fullName: 'Maria Garcia',
    email: 'maria.garcia@barangay.gov.ph',
    phone: '+63 923 456 7890',
    emergencyContact: {
      name: 'Juan Garcia',
      relationship: 'Husband',
      phone: '+63 923 456 7891',
    },
    dateOfBirth: new Date('1990-07-22'),
    address: 'Purok 4, Barangay Hall',
    photo: null,
    status: 'active',
    currentShift: 'night',
    assignedAreas: ['Purok 4-6', 'Market Area'],
    qualifications: ['First Aid Certified', 'Traffic Management'],
    dateJoined: new Date('2021-03-10'),
    rating: 4.9,
    totalIncidentsResponded: 38,
    totalDutyHours: 980,
  },
  {
    id: '3',
    firstName: 'Jose',
    lastName: 'Reyes',
    fullName: 'Jose Reyes',
    email: 'jose.reyes@barangay.gov.ph',
    phone: '+63 934 567 8901',
    emergencyContact: {
      name: 'Ana Reyes',
      relationship: 'Sister',
      phone: '+63 934 567 8902',
    },
    dateOfBirth: new Date('1988-11-05'),
    address: 'Purok 7, Barangay Hall',
    photo: null,
    status: 'on-leave',
    currentShift: 'off',
    assignedAreas: ['Purok 7-9'],
    qualifications: ['First Aid Certified', 'Disaster Response'],
    dateJoined: new Date('2019-06-20'),
    rating: 4.7,
    totalIncidentsResponded: 52,
    totalDutyHours: 1450,
  },
  {
    id: '4',
    firstName: 'Ana',
    lastName: 'Cruz',
    fullName: 'Ana Cruz',
    email: 'ana.cruz@barangay.gov.ph',
    phone: '+63 945 678 9012',
    emergencyContact: {
      name: 'Carlos Cruz',
      relationship: 'Brother',
      phone: '+63 945 678 9013',
    },
    dateOfBirth: new Date('1992-04-18'),
    address: 'Purok 10, Barangay Hall',
    photo: null,
    status: 'active',
    currentShift: 'day',
    assignedAreas: ['Purok 10-12'],
    qualifications: ['First Aid Certified', 'Conflict Resolution'],
    dateJoined: new Date('2022-01-05'),
    rating: 4.6,
    totalIncidentsResponded: 28,
    totalDutyHours: 720,
  },
];

export const mockDutySchedules = [
  {
    id: 'sched-1',
    tanodId: '1',
    tanodName: 'Pedro Santos',
    date: new Date(),
    shift: 'day',
    startTime: '06:00',
    endTime: '18:00',
    patrolArea: 'Purok 1-3',
    status: 'in-progress',
  },
  {
    id: 'sched-2',
    tanodId: '2',
    tanodName: 'Maria Garcia',
    date: new Date(),
    shift: 'night',
    startTime: '18:00',
    endTime: '06:00',
    patrolArea: 'Purok 4-6',
    status: 'scheduled',
  },
  {
    id: 'sched-3',
    tanodId: '4',
    tanodName: 'Ana Cruz',
    date: new Date(Date.now() + 86400000),
    shift: 'day',
    startTime: '06:00',
    endTime: '18:00',
    patrolArea: 'Purok 10-12',
    status: 'scheduled',
  },
];

export const mockAttendanceRecords = [
  {
    id: 'att-1',
    tanodId: '1',
    tanodName: 'Pedro Santos',
    date: new Date(),
    clockIn: new Date(new Date().setHours(6, 0, 0)),
    clockOut: null,
    totalHours: null,
    shift: 'day',
    status: 'on-duty',
    notes: '',
  },
  {
    id: 'att-2',
    tanodId: '2',
    tanodName: 'Maria Garcia',
    date: new Date(Date.now() - 86400000),
    clockIn: new Date(new Date(Date.now() - 86400000).setHours(18, 0, 0)),
    clockOut: new Date(new Date().setHours(6, 0, 0)),
    totalHours: 12,
    shift: 'night',
    status: 'present',
    notes: 'Completed night patrol',
  },
  {
    id: 'att-3',
    tanodId: '4',
    tanodName: 'Ana Cruz',
    date: new Date(Date.now() - 86400000),
    clockIn: new Date(new Date(Date.now() - 86400000).setHours(6, 15, 0)),
    clockOut: new Date(new Date(Date.now() - 86400000).setHours(18, 0, 0)),
    totalHours: 11.75,
    shift: 'day',
    status: 'late',
    notes: '15 minutes late',
  },
];

export const mockIncidentResponses = [
  {
    id: 'inc-resp-1',
    incidentId: 'inc-001',
    tanodId: '1',
    tanodName: 'Pedro Santos',
    incidentType: 'Noise Complaint',
    incidentLocation: 'Purok 2, Block 5',
    reportedAt: new Date(Date.now() - 7200000),
    respondedAt: new Date(Date.now() - 6900000),
    resolvedAt: new Date(Date.now() - 6300000),
    responseTimeMinutes: 5,
    actionsTaken: 'Spoke with residents, mediated conflict, ensured noise levels reduced',
    outcome: 'Successfully resolved - residents agreed to keep noise down',
    severity: 'low',
  },
  {
    id: 'inc-resp-2',
    incidentId: 'inc-002',
    tanodId: '2',
    tanodName: 'Maria Garcia',
    incidentType: 'Suspicious Activity',
    incidentLocation: 'Market Area, Stall 12',
    reportedAt: new Date(Date.now() - 86400000),
    respondedAt: new Date(Date.now() - 86100000),
    resolvedAt: new Date(Date.now() - 84600000),
    responseTimeMinutes: 5,
    actionsTaken: 'Investigated area, questioned individuals, coordinated with authorities',
    outcome: 'Identified suspects, reported to police for follow-up',
    severity: 'medium',
  },
  {
    id: 'inc-resp-3',
    incidentId: 'inc-003',
    tanodId: '1',
    tanodName: 'Pedro Santos',
    incidentType: 'Medical Emergency',
    incidentLocation: 'Purok 3, House 45',
    reportedAt: new Date(Date.now() - 172800000),
    respondedAt: new Date(Date.now() - 172560000),
    resolvedAt: new Date(Date.now() - 171000000),
    responseTimeMinutes: 4,
    actionsTaken: 'Provided first aid, called ambulance, stayed with patient until help arrived',
    outcome: 'Patient transported to hospital, family notified',
    severity: 'high',
  },
  {
    id: 'inc-resp-4',
    incidentId: 'inc-004',
    tanodId: '4',
    tanodName: 'Ana Cruz',
    incidentType: 'Traffic Incident',
    incidentLocation: 'Main Road intersection',
    reportedAt: new Date(Date.now() - 259200000),
    respondedAt: new Date(Date.now() - 258900000),
    resolvedAt: new Date(Date.now() - 257400000),
    responseTimeMinutes: 5,
    actionsTaken: 'Directed traffic, coordinated vehicle removal, documented incident',
    outcome: 'Road cleared, minor property damage, no injuries',
    severity: 'medium',
  },
];

export const mockPatrolAreas = [
  {
    id: 'area-1',
    name: 'Purok 1-3',
    coordinates: [
      [14.5995, 120.9842],
      [14.5996, 120.9852],
      [14.5985, 120.9853],
      [14.5984, 120.9843],
    ],
    assignedTanodIds: ['1'],
    priority: 'high',
  },
  {
    id: 'area-2',
    name: 'Purok 4-6',
    coordinates: [
      [14.5985, 120.9852],
      [14.5986, 120.9862],
      [14.5975, 120.9863],
      [14.5974, 120.9853],
    ],
    assignedTanodIds: ['2'],
    priority: 'medium',
  },
  {
    id: 'area-3',
    name: 'Market Area',
    coordinates: [
      [14.6005, 120.9832],
      [14.6006, 120.9842],
      [14.5995, 120.9843],
      [14.5994, 120.9833],
    ],
    assignedTanodIds: ['2'],
    priority: 'high',
  },
  {
    id: 'area-4',
    name: 'Purok 7-9',
    coordinates: [
      [14.5975, 120.9862],
      [14.5976, 120.9872],
      [14.5965, 120.9873],
      [14.5964, 120.9863],
    ],
    assignedTanodIds: [],
    priority: 'low',
  },
  {
    id: 'area-5',
    name: 'Purok 10-12',
    coordinates: [
      [14.5965, 120.9872],
      [14.5966, 120.9882],
      [14.5955, 120.9883],
      [14.5954, 120.9873],
    ],
    assignedTanodIds: ['4'],
    priority: 'medium',
  },
];
